$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "github-context.ps1")

$repoRoot = Get-ForsettiRepoRoot
$event = Get-ForsettiGitHubEvent
$body = Get-ForsettiPullRequestBody -Event $event
$eventName = if ($env:GITHUB_EVENT_NAME) { $env:GITHUB_EVENT_NAME } else { "" }

$baseSha = ""
$headSha = ""
if ($event -and $event.pull_request) {
    $baseSha = [string]$event.pull_request.base.sha
    $headSha = [string]$event.pull_request.head.sha
} elseif ($event -and $event.before -and $event.after) {
    $baseSha = [string]$event.before
    $headSha = [string]$event.after
}
if ([string]::IsNullOrWhiteSpace($baseSha) -or $baseSha -match '^0+$' -or [string]::IsNullOrWhiteSpace($headSha)) {
    $baseSha = "HEAD~1"
    $headSha = "HEAD"
}

$coauthorPatterns = @("bot", "assistant", "automation", "generated", "tool", "model", "vendor")
$emailPatterns = @("bot@.*", "assistant", "automation", "generated", "tool", "model", "vendor")
$namePatterns = @(".*bot.*", ".*assistant.*", ".*automation.*", ".*generated.*", ".*tool.*", ".*model.*", ".*vendor.*")
$prBodyPatterns = @("generated with", "generated by", "generated-by-tool", "co-authored[- ]by", "assisted by", "authored by", "thanks to")

$violations = New-Object System.Collections.Generic.List[string]

Write-Host "=== Checking commit messages for restricted co-author trailers ==="
$logLines = @(& git -C $repoRoot log --format="%H%n%B" "$baseSha..$headSha" 2>$null)
$current = ""
foreach ($line in $logLines) {
    if ($line -match '^[a-f0-9]{40}$') {
        $current = $line.Substring(0, 7)
        continue
    }
    foreach ($pattern in $coauthorPatterns) {
        if ($line -match "(?i)co-authored[- ]by.*$pattern") {
            $violations.Add("Commit ${current}: co-author trailer matches restricted pattern.")
            break
        }
    }
}

Write-Host "=== Checking commit author/committer emails ==="
$emailLines = @(& git -C $repoRoot log --format="%H|%ae|%ce" "$baseSha..$headSha" 2>$null)
foreach ($line in $emailLines) {
    $parts = $line -split '\|', 3
    if ($parts.Count -lt 3) { continue }
    $short = $parts[0].Substring(0, 7)
    foreach ($pattern in $emailPatterns) {
        if ($parts[1] -match "(?i)$pattern" -or $parts[2] -match "(?i)$pattern") {
            $violations.Add("Commit ${short}: author or committer email matches restricted pattern.")
            break
        }
    }
}

Write-Host "=== Checking commit author/committer names ==="
$nameLines = @(& git -C $repoRoot log --format="%H|%an|%cn" "$baseSha..$headSha" 2>$null)
foreach ($line in $nameLines) {
    $parts = $line -split '\|', 3
    if ($parts.Count -lt 3) { continue }
    $short = $parts[0].Substring(0, 7)
    foreach ($pattern in $namePatterns) {
        if ($parts[1] -match "(?i)$pattern" -or $parts[2] -match "(?i)$pattern") {
            $violations.Add("Commit ${short}: author or committer name matches restricted pattern.")
            break
        }
    }
}

if ($eventName -eq "pull_request" -and -not [string]::IsNullOrWhiteSpace($body)) {
    Write-Host "=== Checking PR body for attribution ==="
    foreach ($pattern in $prBodyPatterns) {
        if ($body -match "(?i)$pattern") {
            $violations.Add("PR body contains restricted attribution language.")
            break
        }
    }
}

if ($violations.Count -gt 0) {
    foreach ($violation in $violations) {
        Write-Error $violation
    }
    exit 1
}

Write-Host "No restricted contributor attribution detected. Guard passed."
